# words list from which to derive mnemonic for SEED retrieval. 4096 words. Thus a 48 byte SEED can be represented by 32 words..

__author__ = 'pete'

wordlist = ['aalii', 'aals', 'abaci', 'abamp', 'aband', 'abased', 'abbasi',
            'abbot', 'abed', 'abidi', 'abient', 'abigei', 'abkar', 'abrico',
            'absume', 'abut', 'acapu', 'acara', 'accoil', 'accts', 'accupy', 'accus',
            'achar', 'ache', 'achime', 'achira', 'achkan', 'acinus', 'ackee',
            'ackees', 'acoin', 'acool', 'acoria', 'acre', 'acred', 'actg',
            'actine', 'actual', 'acumen', 'adams', 'addend', 'addled', 'adead', 'adept',
            'admrx', 'adnex', 'adobo', 'adoze', 'adread', 'adytum', 'adze',
            'aegean', 'aeneas', 'afeard', 'affere', 'affies', 'affuse', 'afreet',
            'africa', 'afrite', 'afros', 'agape', 'agate', 'agave', 'agen',
            'agha', 'agin', 'agisms', 'agist', 'agists', 'agrito', 'agua', 'agura',
            'ahems', 'ahey', 'aide', 'aides', 'aigre', 'aimak', 'aimful', 'aims', 'aire',
            'aired', 'airier', 'aisle', 'aisles', 'ajhar', 'ajugas', 'aked',
            'alan', 'alang', 'alant', 'alanyl', 'alapa', 'alarm', 'alcids', 'aldol',
            'alecs', 'algas', 'algate', 'algic', 'algous', 'alight', 'align',
            'alive', 'alkyne', 'allen', 'almeh', 'almugs', 'alnage', 'alnein',
            'aloed', 'aloes', 'aloft', 'alphyn', 'alroot', 'altin', 'alto', 'alular',
            'alumin', 'alvus', 'alypum', 'amaga', 'amar', 'amarin', 'amarna',
            'amas', 'amazia', 'ambles', 'ambos', 'ambury', 'amend', 'amende', 'amenia',
            'amens', 'amias', 'amice', 'amies', 'amimia', 'amine', 'amins',
            'amiray', 'amis', 'amnic', 'amobyr', 'amoeba', 'amoved', 'ampule', 'amtmen',
            'amulae', 'amusee', 'amuses', 'amylon', 'anally', 'ancora',
            'andia', 'anenst', 'angel', 'angels', 'angle', 'angora', 'angst', 'anion',
            'anjan', 'ankara', 'annary', 'annats', 'anneal', 'annist', 'annot', 'anodes',
            'anour', 'anre', 'ansa', "ant", 'anural', 'anus', 'anyway',
            'aortal', 'aouad', 'apart', 'aped', 'apeek', 'aphtha', 'apiole', 'apish',
            'apneas', 'apogee', 'aponic', 'appast', 'appd', 'apport',
            'arabia', 'arad', 'arage', 'arcady', 'ardor', 'areca', 'arecas', 'arest',
            'argali', 'argema', 'argons', 'arid', 'arilli', 'arnold',
            'arnut', 'aroon', 'arri', 'arroba', 'arsino', 'artaba', 'artabe', 'arthra',
            'arui', 'arumin', 'aryan', 'arzan', 'asarta', 'ashen', 'ashier',
            'ashing', 'ashot', 'asides', 'askoi', 'aslake', 'asor', 'aspens',
            'aspic', 'assai', 'assam', 'assary', 'assurd', 'astate', 'astely', 'aswing',
            'atar', 'athrob', 'atli', 'atman', 'atomy', 'atony', 'atreus',
            'atrip', 'attask', 'atteal', 'attrap', 'atune', 'atwain', 'aubain', 'aube',
            'auklet', 'aulas', 'aullay', 'auntly', 'aurata', 'aurei',
            'aurify', 'aurure', "auto", 'autoed', 'autumn', 'avaram', 'aveloz', 'avows',
            'awacs', 'awed', "awl", 'axer', 'axin', 'axons', 'ayahs',
            'azonal', 'azonic', 'azotin', 'aztec', 'azures', 'babbie', 'baboo', 'babul',
            'bacony', 'bade', 'bagass', 'bagnes', 'bailo', 'bairdi',
            'baizas', 'bajury', 'bakshi', 'bale', 'balei', 'balkan', 'ballet', 'ballo',
            'balr', 'baltei', 'banger', 'banig', 'baniya', 'banter', 'banty',
            'barad', 'barbe', 'barche', 'barded', 'barhal', 'barit', 'barky', 'barlow',
            'barms', 'barny', 'barrer', 'basalt', 'basat', 'base', 'based',
            'basher', 'basils', 'basked', 'bassia', 'basta', 'bastes', 'batons', 'batt',
            'batton', 'batts', 'batzen', 'baud', 'baul', 'baun', 'bawty',
            'bayard', 'beach', 'beak', 'beasts', 'beatas', 'becchi', 'beclad', 'becut',
            'bedead', 'bedrel', 'bedrip', 'bedrop', 'bedub', 'beech', 'beeps',
            'beet', 'beetle', 'befits', 'behint', 'behoof', 'behorn', 'bejan', 'belay',
            'bemail', 'bemete', 'bemix', 'bents', 'bepray', 'bere', 'berime',
            'berith', 'berob', 'besew', 'beslur', 'besped', 'bespot', 'best', 'besugo',
            'beta', 'betorn', 'beulah', 'bework', 'beworn', 'bezels', 'bhoy',
            'bialy', 'bialys', 'bibbs', 'bichy', "bid", 'bider', 'bides', 'bidi',
            'bifid', 'bigger', 'bigwig', 'bijou', "bike", 'bikh', 'billet', 'bima',
            'bimbil', 'binal', 'bing', 'bingey', 'bingle', 'binits', 'bink', 'binmen',
            'bins', 'bipack', 'birks', 'bish', 'bist', 'bisync', 'biter', 'biters',
            'biting', 'biuret', 'bize', 'blacks', 'blamer', 'blanco', 'blashy', 'blason',
            'blawn', 'blazed', 'bleach', 'blee', 'bleeps', 'bless', 'blet', 'blonds',
            'blowze', 'blunk', 'blurb', 'blusht', 'bobber', 'bobfly', 'boce', 'boches',
            'bodger', 'boget', 'bogey', 'bohawn', 'boiled', 'boise', 'bojite', 'bolder',
            'boled', 'bolete', 'bombe', 'bombes', 'bonair', 'bonito', 'bonsai', 'boohoo',
            'boonk', 'boor', 'booted', 'bopeep', 'bops', 'bora', 'boreal', 'boride',
            'borism', 'bornan', 'bornyl', 'boro', 'borons', 'boryl', 'bosey', 'bosser',
            'botel', 'botong', 'bouch', 'bouk', 'boukit', 'bouse', 'bouto', 'bouts',
            'bowle', 'bowpin', 'bows', 'bowyer', 'boxful', "boy", 'brairo',
            'brame', 'branks', 'brants', 'brast', 'bratty', 'braver', 'brawn', 'bray',
            'breech', 'brees', 'breton', 'bricks', 'bries', 'briss', 'brits',
            'britts', 'broad', 'brocht', 'bronx', 'bronzy', 'broo', 'brook', 'broon',
            'broos', 'broses', 'brosse', 'browd', 'brules', 'brunch',
            'bryan', 'bubas', 'bubby', 'buckie', 'buddle', 'bude', 'budgy', 'buds',
            'bugeye', 'bugre', 'bulby', 'bulse', "bun", 'bungfu', 'bungy',
            'bunker', 'bunny', 'burbot', 'burka', 'burled', 'buro', 'burree', 'burrs',
            'bursar', 'bushet', 'bushy', 'busket', 'buskle', 'bussy',
            'bustee', 'butoxy', "butt", 'buyout', 'buzzed', 'byname', 'byrlaw',
            'byrrus', 'caama', 'cabaho', 'cabful', 'cabins', 'cabre', 'cacoon', 'cactus',
            'cacur', 'cadee', 'cader', 'cadew', 'cadgy', 'cadis', 'caffoy', 'caffre',
            'cahier', 'caid', 'cajon', 'cakey', 'calami', 'calces', 'calci', 'calfs',
            'calico', 'caliga', 'calix', 'calmed', 'calmy', 'calx', 'camb', 'came',
            'camery', 'camper', 'canc', 'canch', 'canham', 'canid', 'cannet', 'canoed',
            'canton', 'canuck', 'capax', 'capon', 'capot', 'caps', 'carapo', 'carboy',
            'carded', 'careen', 'carex', 'carful', 'carlo', 'carne', 'carole', 'carp',
            'carrel', 'carrus', 'carrys', 'cars', 'carvy', 'casa', 'casco', 'case',
            'cashaw', 'casina', 'casino', 'cask', 'cassan', 'casshe', 'cassis', 'casula',
            'casus', 'cate', 'catena', 'catnap', 'catnep', 'caudad', 'causse', 'cavate',
            'cawney', 'cawny', 'cebus', 'ceca', 'cedens', 'ceding', 'cedrin',
            'ceiba', 'ceibo', 'ceint', 'ceja', 'celebe', 'cenote', 'cercle', 'ceric',
            'ceste', 'cetera', 'cetus', 'chaco', 'chaft', 'chakar', 'chakra',
            'cham', 'chams', 'charas', 'chared', 'chark', 'charm', 'charnu', 'chary',
            'chauri', 'chave', 'cheat', 'checke', 'cheer', 'cheero',
            'cheesy', "chef", 'cheka', 'chere', 'cherem', 'cherry', 'cherts', 'cherub',
            'chess', 'chetty', 'chewer', 'chibol', 'chilly', 'chiral', 'chirps',
            'choil', 'chol', 'chorei', 'chous', 'chromy', 'chumps', 'chunky', 'churm',
            'chute', 'chyme', 'cicer', 'cimex', 'cinch', 'cions', 'cisium', 'ciudad',
            'civets', 'civism', 'clach', 'clack', 'clad', 'claims', 'claith', 'clams',
            'clasp', 'claus', 'clay', 'claye', 'cleeks', 'clef', 'cleuks', 'clewed',
            'client', 'cliffs', 'clings', 'clinid', 'clipt', 'cliquy', 'clithe', 'cliver',
            'clod', 'clomp', 'clops', 'clos', 'clou', 'clouds', 'cloudy', 'clours',
            'clove', 'cloy', 'coagel', 'coarct', 'coaxy', 'cobaea', 'cobalt', 'cobb',
            'cobia', 'coco', 'cocoon', 'coddy', 'code', 'coelar', 'coggly', 'cogida',
            'cold', 'colds', 'colera', 'coleur', 'colin', 'collab', 'collie',
            'collow', 'cologs', 'color', 'combe', 'combes', 'combo', 'comboy', 'comida',
            'commos', 'comte', 'comus', 'comvia', 'coneen', 'conima',
            'conins', 'conks', 'contos', 'convoy', 'cooed', 'coof', 'coofs', 'coots',
            'copal', 'copart', 'coppet', 'coppy', 'copr', 'cops', 'coral',
            'corbe', 'corer', 'cormus', 'cornic', 'corody', 'correo', 'corse', 'coryph',
            'cosecs', 'coshes', 'cosin', 'cossid', 'costly', "cot", 'cotan',
            'cotans', 'cotery', 'cotes', 'coth', 'cothe', 'coto', 'cotoro', 'cott',
            'cotty', 'cougar', 'coughs', 'coul', 'could', 'coup', 'courge', 'covid',
            'cowers', 'cozed', 'cozens', 'crabby', 'cracks', 'cradle',
            'craie', 'crane', 'craned', 'crank', 'crapy', 'creach', 'creche', 'credo',
            'creeks', 'crepis', 'cresc', 'crest', 'crewel', 'crinet',
            'crink', 'croft', 'crop', 'crore', 'crotin', 'crouke', 'croupe', 'crow',
            'crts', 'cruche', 'cruck', 'cruent', 'cruet', 'crumby', 'crunt',
            'cruset', 'cryst', 'cuba', 'cubdom', 'cuber', 'cuda', 'cuddly', 'cuecas',
            'cueman', 'cues', 'cuffle', 'cuish', 'cuke', 'culet', 'culmy', 'cunit',
            'cupful', 'cupid', 'cupper', 'curby', 'cures', 'curie', 'curium',
            'curn', 'curpel', 'cururo', 'curvey', 'curvy', 'cury', 'cusp', 'custos',
            'cutlet', 'cutty', 'cuyas', 'cyanea', 'cyanid', 'cyclas',
            'cycled', 'cyclus', 'cymba', 'cymbel', 'cymule', 'cynic', 'cypre', 'cyrus',
            'cystis', 'cytons', 'dabuh', 'daemon', 'dagame', 'dahlin', 'daidle', 'daisee',
            'daises', 'dalan', 'dali', "dam", 'damier', 'dams', 'damson', 'dances',
            'darg', 'darger', 'darken', 'darner', 'darnix', 'dashed', 'dasher', 'dates',
            'daubs', 'daud', 'daurna', 'david', 'davis', 'dawtit', 'daybed', 'daying',
            'dazing', 'deaf', 'deafer', 'dearer', 'debord', 'debtor', 'debye', 'decide',
            'deck', 'decker', 'defeit', 'deflow', 'defoul', 'degame', 'degree', 'deisms',
            'deixis', 'delies', 'delime', 'deluce', 'deluxe', 'demele', 'demode', 'demur',
            'denaro', 'denize', 'dentel', 'dentex', 'dentin', 'dents', 'depe', 'depots',
            'desalt', 'desand', 'descry', 'desi', 'desks', 'desmid', 'desto', 'dette',
            'deul', 'deuton', 'deuzan', 'devil', 'dewar', 'dewcap', 'dewtry', 'deynt',
            'dhauri', 'dhotee', 'dhows', 'diaka', 'diazo', 'dibase', 'dick', 'diddy',
            'didie', "did", 'diked', 'dilis', 'dindon', 'dine', 'ding', 'dinge',
            'dinos', 'diodes', 'dioecy', 'diols', 'dioxin', 'dirgie', 'dirhem', 'dirks',
            'dirt', 'dirty', 'disher', 'disks', 'dislip', 'disown', 'dist', 'dived',
            'divell', 'diver', 'divine', 'divort', 'divot', 'diwata', 'dixies', 'dixit',
            'doand', 'doats', 'dodoma', 'doest', 'dogal', 'doge', 'dogget', 'doigt',
            'doings', 'dojos', "do", 'doncy', 'donet', 'donna', 'donne', 'donnot',
            'donny', 'donsky', 'donsy', 'doodah', 'dooli', 'doon', 'dopant', 'dope',
            'doper', 'doray', 'dorbel', 'dories', 'dort', 'dosain', 'doses', 'doss',
            'dossy', 'dother', 'dotlet', 'dotted', 'douche', 'doughs', 'dougl', 'doura',
            'douse', 'doves', 'dowcet', 'dowl', 'dowses', 'dowset', 'doyly', 'dozy',
            'dracma', 'draine', 'drake', 'drats', 'dreep', 'dreynt', 'drie', 'drinks',
            'droh', 'droll', 'drolls', 'dromoi', 'drones', 'droop', 'droud', 'drupes',
            'dtente', 'dtset', 'duali', 'dubbed', 'dude', 'dueful', 'duits', 'dukker',
            'dulias', 'dumbly', 'dunair', 'dune', 'dunger', 'dungs', 'dunks', 'dunlin',
            'durain', 'dured', 'durity', 'durry', 'dusk', 'dusts', 'dusty', 'dwale',
            'dwells', 'dyak', 'dybbuk', 'dyce', 'dying', 'dyking', 'dynam', 'dynel',
            'dysury', 'eadish', 'eagle', 'eaning', 'earful', 'earlap', 'echo', 'ecole',
            'eczema', 'eerock', 'egads', 'egests', 'egis', 'egoity', 'ehrman', 'eident',
            'eidos', 'eila', 'eisell', 'elamp', 'elanet', 'elders', 'eldin', 'elding',
            'eleme', 'elenge', 'elfdom', 'eltrot', 'elysia', 'elytra', 'ember', 'embira',
            'embost', 'embow', 'embue', 'emer', 'emerod', 'emery', 'emmies', 'emoted',
            'emunct', 'emus', 'enapt', 'enbibe', 'encase', 'encowl', 'encup', 'endura',
            'enfirm', 'enfork', 'enhelm', 'enigua', 'enlace', 'enlink', 'enmass', 'entre',
            'envaye', 'enweb', 'enwood', 'enzyme', 'eole', 'ephete', 'epicly', 'epilog',
            'epitra', 'epocha', 'epoist', 'eponge', 'epopt', 'epsom', 'erato', 'erinys',
            'errsyn', 'eruc', 'erugo', 'erupts', 'esnecy', 'espec', 'essede', 'estamp',
            'eton', 'etrogs', 'etwas', 'etwees', 'etymon', 'etypic', 'evacue', 'evader',
            'evermo', 'excuse', 'exequy', 'exeunt', 'exhort', 'expand', 'explat',
            'export', 'exsert', 'exship', 'exter', 'extine', 'extirp', 'eyass', 'eyepit',
            'eying', 'eyra', 'eyrer', 'facets', 'fack', 'faddy', 'faded', 'faders',
            'fading', 'failed', 'faisan', 'fakeer', 'fakery', 'falk', 'falun', 'famish',
            'fancy', 'fangas', 'fangy', 'fanion', 'fankle', 'farcie', 'farde', 'farded',
            'faroff', 'farted', 'farth', 'fascia', 'fasels', 'fasts', 'fating', 'faute',
            'fauves', 'faux', 'fawner', 'fawns', 'fealty', 'feared', 'feasts', 'feaze',
            'feeds', 'feint', 'felix', 'femes', 'feodum', 'fere', 'ferrel', 'fervid',
            'feted', 'fetich', 'feued', 'fezes', 'fezzy', 'fiefs', 'fifers', 'filing',
            'filius', 'film', 'finest', 'fining', 'finned', 'finny', 'firmly', 'firsts',
            'fisher', 'fisk', 'fitted', 'flagon', 'flail', 'flans', 'flappy', 'flathe',
            'flatly', 'flaunt', 'fleak', 'fleamy', 'flect', 'fliers', 'flinch', 'flirts',
            'flisky', 'flit', 'floats', 'floaty', 'flobby', 'flocs', 'fluky', 'flunk',
            'flutey', 'fluvio', 'flying', 'fobs', 'focus', 'fogs', 'foiler', 'foined',
            'foment', 'fondus', "font", 'fooder', 'fooler', 'footsy', 'fopped', 'foppy',
            'forby', 'force', 'forcy', 'fordam', 'fordo', 'foret', 'forlet', 'former',
            'forset', 'fotive', 'foud', 'fought', 'fouth', 'fowage', 'foyer', 'frack',
            'framed', 'framer', 'francs', 'frap', 'frase', 'fraser', 'frauen', 'frays',
            'fream', 'freddo', 'freer', 'freir', 'freith', 'frenne', 'fresh', 'fress',
            'frets', 'friar', 'frill', 'friths', 'frizz', 'frokin', 'fronds', 'frosh',
            'frosty', 'froths', 'froust', 'frouze', 'frow', 'frowze', 'fryer', 'fudgy',
            'fugles', 'fugu', 'fugue', 'fuhrer', 'fulgid', 'fumant', 'funded', 'funge',
            'fungi', "fur", 'furcal', 'furls', 'furner', 'furred', 'fury', 'fuseau',
            'fussed', 'fussy', 'fykes', 'gabert', 'gable', 'gables', 'gader', 'gadids',
            'gael', 'gaet', 'gaffe', 'gagger', 'gaging', 'galah', 'galeas', 'galey',
            'galled', 'gallop', 'gallow', 'galoch', 'galops', 'gambit', 'gambs', 'gamely',
            'gamily', 'gammed', 'gammon', 'gamori', 'gane', 'ganges', 'ganoid', 'ganzie',
            'gaoled', 'garau', 'gardon', 'gareh', 'garget', 'garn', 'gars', 'gast',
            'gastly', 'gaup', 'gauzy', 'gavels', 'gawn', 'gayest', 'gayly', 'geared',
            'gedder', 'geek', 'gelate', 'gelded', 'gelder', 'gemel', 'gemmer', 'genic',
            'genion', 'genome', 'gently', 'gentoo', 'geotic', 'gerkin', "germ",
            'gersum', 'getter', 'gharri', 'ghazel', 'ghbor', 'giants', 'gibing', 'gigger',
            'giglet', 'gilled', 'gils', 'gimlet', 'gimmer', 'gimmor', 'gingko', 'ginner',
            'gipons', 'gipper', 'girdle', 'girds', 'girny', 'gismos', 'giusto', 'glades',
            'glazed', 'gleans', 'gleary', 'glen', 'glimed', 'gloeal', 'glome', 'glovey',
            'gluck', 'gluing', 'glycin', 'gnarly', 'gnarrs', 'gnash', 'gnatty', 'gnomes',
            'gocart', 'godiva', 'goldie', 'golem', 'goles', 'goller', 'gollop', 'golly',
            'golosh', 'gomart', 'gomlah', 'gonad', 'gond', 'goody', 'goofy', 'goonch',
            'gorer', 'gorier', 'gosh', 'goshen', 'gossep', 'gossy', 'goths', 'gove',
            'gowan', 'gowdy', 'gowlan', 'grade', 'grader', 'gram', 'gramas', 'grame',
            'granes', 'grano', 'grates', 'graven', 'greese', 'grege', 'greige', 'greing',
            'grill', 'grinds', 'gringo', 'gripe', 'grise', 'gromet', 'groped', 'gropes',
            'gruels', 'grumes', 'grumph', 'grumps', 'gruys', 'guadua', 'guama', 'gucks',
            'guess', 'guests', 'gugal', 'guggle', 'guider', 'guild', 'guilts', 'gulae',
            'guly', 'gums', 'gunung', 'gunyah', 'gurkha', 'gursh', 'gusain', 'guts',
            'guyots', 'gweed', 'gweeon', 'gybe', 'gyrene', 'gyroma', 'gyrous', 'gyving',
            'hade', 'hades', 'hadjee', 'haem', 'haemin', 'haet', 'haflin', 'hafter',
            'haggai', 'haikai', 'haikal', 'haint', 'haire', 'hairof', 'haku', 'halide',
            'halloa', 'halt', 'hamada', 'hands', 'hang', 'hansom', 'haply', 'happed',
            'haps', 'hared', 'harem', 'hares', 'harm', 'harold', 'harpin', 'harvey',
            'hashed', 'hasid', 'hasn', 'hasty', 'hated', 'hater', 'hatted', 'haught',
            'haybox', 'haymow', 'hays', 'hazans', 'hazels', 'hazle', 'headly', 'heat',
            'heathy', 'heats', 'hector', 'hedgy', 'heel', 'heezy', 'hefted', 'hegira',
            'heil', 'heinie', 'heirs', 'heling', 'hello', 'helm', 'heloma', 'helves',
            'hemoid', 'hempen', 'henen', 'here', 'hereto', 'hernia', 'hers', 'hery',
            'hesped', 'heth', 'heugh', 'hewer', 'hexane', 'hexene', 'heypen', 'hiate',
            'hiders', 'hides', 'hikes', 'hiking', 'hili', "hill", 'hilled', 'hilt',
            'hinney', 'hinoid', 'hints', 'hipple', 'hiren', 'hish', 'hist', 'hists',
            'hizzie', 'hoared', 'hoars', 'hoaxee', 'hobbil', 'hoblob', 'hogpen', 'hoho',
            'hoking', 'hola', 'hollo', 'holmes', 'holp', 'hominy', 'homo', 'honked',
            'hooch', 'hooeys', 'hoofed', 'hoofer', 'hoofs', 'hoops', 'hootay', 'hopi',
            'hopper', 'horde', 'hore', 'hors', 'horste', 'horsy', 'hosels', 'hotels',
            'hoult', 'hounds', 'houss', 'housty', 'howl', 'howlet', 'hoyles', 'hubbed',
            'hubris', 'hugger', 'hulled', 'huly', 'humor', 'hunh', 'hunter', 'huppah',
            'hurley', 'hurry', 'husks', 'hutia', 'hutre', 'huxter', 'huzoor', 'hyetal',
            'hyphal', 'hypnum', 'iamb', 'iambs', 'iare', 'icbm', 'icemen', 'icier',
            'iciest', 'icing', 'ickers', 'icod', 'idaein', 'idgah', 'idiasm', 'idic',
            'idiocy', 'idion', 'idleby', 'idylls', 'ifecks', 'igad', 'ikon', 'ikra',
            'ileal', 'illect', 'imaums', 'imbeds', 'imbrex', 'imdtly', 'imine', 'imit',
            'immew', 'immund', 'impalm', 'impede', 'impend', 'imper', 'imperf', 'inact',
            'inaja', 'inane', 'inark', 'incage', 'incast', 'incept', 'incide', 'indent',
            'indic', 'indin', 'indoor', 'inface', 'infare', 'infect', 'infeed', 'infeft',
            'inform', 'inglut', 'inhale', 'inhive', 'injury', 'inkers', 'inks', 'inlike',
            'inmore', 'innage', 'inogen', 'inpush', 'insee', 'inst', 'intact', 'intine',
            'intown', 'inulin', 'invite', 'iodic', 'iodite', 'ions', 'iortn', 'iowa',
            'ipecac', 'irades', 'irbis', 'irchin', "ire", 'irene', 'iritic', 'irous',
            "is", 'isnt', 'issite', 'istles', 'italy', 'ivies', 'izars', "jab",
            'jabble', 'jacky', 'jacu', 'jaeger', 'jager', 'jagers', 'jajman', 'jalops',
            'jalur', 'jamoke', 'jampan', 'janker', 'jantu', 'jaob', 'jarbot', 'jarry',
            'jason', 'jawed', 'jeames', 'jean', 'jebels', 'jeed', 'jeel', 'jehads',
            'jelib', 'jellab', 'jellib', 'jenna', 'jennie', 'jerez', 'jerks', 'jerl',
            'jester', 'jeziah', 'jibbed', 'jibs', 'jicama', 'jigmen', 'jilter', 'jina',
            'jink', 'joan', 'jobbed', 'jokers', 'jolted', 'jordan', 'joseph', 'josh',
            'josser', 'joual', 'joug', 'jouncy', 'joys', 'juba', 'juiced', 'juloid',
            "july", 'jumba', 'jumble', 'jump', 'junker', 'juntas', 'jurats', 'juster',
            'justly', 'kabar', 'kabiet', 'kabob', 'kabs', 'kadaya', 'kadine', 'kahar',
            'kahili', 'kaiser', 'kalams', 'kalo', 'kalpak', 'kamahi', 'kame', 'kamias',
            'kanaka', 'kanas', 'kapoks', 'karmas', 'karns', 'karos', 'karroo', 'kart',
            'karvar', 'kauch', 'kauri', 'kays', 'kebby', 'kedged', 'keefs', 'keeks',
            'keens', 'kegs', 'keist', 'kelder', 'kellet', 'kelp', 'kelpy', 'kench',
            'kept', 'kerel', 'kero', 'keten', 'keup', 'kexy', 'keylet', 'keyman',
            'keymen', 'khan', 'kicky', "kid", 'kidang', 'kidlet', 'kikuel', 'kilah',
            'kilij', 'killas', 'killcu', 'kilty', 'kimnel', 'kinbot', 'kindle', 'kinhin',
            'kinoos', 'kippen', 'kipper', 'kirks', 'kirn', 'kittel', 'kitty', 'klong',
            'kluck', 'kmel', 'knarle', 'knarry', 'knars', 'knees', 'knetch', 'knight',
            'knits', 'knops', 'knowns', 'knows', 'knubby', 'knucks', 'koali', 'kobu',
            'kokum', 'kolas', 'kookie', 'koolah', 'kopeks', 'koppie', 'korai', 'kosher',
            'kouros', 'krigia', 'krome', 'krone', 'kuchen', 'kudos', 'kuge', 'kukui',
            'kunkur', 'kupper', 'kusso', 'kussos', 'kvass', 'kyacks', 'kyat', 'label',
            'labile', 'labra', 'labrum', 'lacoca', 'lactim', 'ladens', 'lader', 'ladies',
            'ladin', 'ladner', 'lads', 'laggen', 'laics', 'laid', 'laine', 'lairds',
            'laiser', 'laith', 'lakey', 'lakish', 'laky', 'lamaic', 'lamb', 'lampic',
            'langel', 'langka', 'lansat', 'lant', 'lanx', 'laodah', 'laos', 'lapins',
            'lapses', 'lard', 'lare', 'larger', 'larnax', 'larnyx', 'larums', 'lashes',
            'lasso', 'lata', 'lathed', 'lathee', 'lati', 'lation', 'lative', 'laton',
            'latria', 'laughs', 'lauia', 'laur', 'laved', 'lawish', 'lawns', 'layed',
            'lazied', 'leafed', 'league', 'lean', 'lecama', 'lech', 'leed', 'leeds',
            'legals', 'lekane', 'lelwel', 'lemma', 'lend', 'lendee', 'lenses', 'lenten',
            'leon', 'lepero', 'leppy', 'leptid', 'lese', "liar", 'libber', 'libs',
            'lich', 'licury', 'ligand', 'light', 'ligule', 'ligure', 'lilts', 'limed',
            'limens', 'limer', 'limine', 'limmer', 'limos', 'limose', 'limply', 'lintie',
            'lipic', 'lirate', 'litz', 'lived', 'livery', 'ller', 'loan', 'lobby', 'lobs',
            'locums', 'locust', 'loft', "lofty", 'logie', 'logis', 'logoi', 'longa',
            'looeys', 'lookup', 'looney', 'loover', 'loping', 'lopped', 'loppet', "lor",
            'lord', 'lory', 'lose', 'lota', 'lotas', 'lotion', 'lotto', 'louie', 'loungy',
            'loury', 'lousy', 'louty', 'loves', 'lowed', 'lowest', 'lowly', 'loxia',
            'loyal', 'lubra', 'lucre', 'luffs', 'luggar', 'lunier', 'lunn', 'lupoma',
            'lurdan', 'lusts', 'lutes', 'lwop', 'lyings', 'lynch', 'lyssa', 'lytic',
            'lyttae', 'mabolo', 'mabyer', 'macaw', 'mach', 'madefy', 'madge', 'madhab',
            'madly', 'madroa', 'mads', 'maed', 'maes', 'magnum', 'maha', 'mahdi', 'maile',
            'maimer', 'mainly', 'malapi', 'malgr', 'malmy', 'maltha', 'mambo', 'mamma',
            'mammet', 'mammey', 'mangi', 'mangle', 'mangue', 'mania', 'manism', 'mantra',
            'mapach', 'maquis', 'marcel', 'mark', 'marly', 'marmit', 'marok', 'marten',
            'mascon', 'mascot', 'mashed', 'mask', 'masons', 'massas', 'mather', 'matin',
            'matina', 'matra', 'matts', 'maundy', 'mazame', 'mazdur', 'mazier', 'meanie',
            'meany', 'medino', 'meece', 'meets', 'mein', 'meith', 'mekong', 'meloe',
            'mendel', 'meng', 'mensae', 'mentor', 'menu', 'menyie', 'mercy', 'merd',
            'merest', 'merida', 'mermen', 'meshed', 'mesic', 'mesked', 'meslen', 'metel',
            'methol', 'meths', 'methyl', 'metic', 'metis', 'metron', 'miaou', 'miaow',
            'mias', 'miched', 'mickle', 'micky', 'micra', 'mids', 'miffs', 'migg',
            'milder', 'mildly', 'milly', 'mimeo', 'mimeos', 'minder', 'mingle', 'mingy',
            'minhah', 'mink', 'minty', 'mirdha', 'mirs', 'mirths', 'miscue', 'misgye',
            'misrun', 'miss', 'missa', 'missed', 'miter', 'mitral', 'mitt', 'mizzly',
            'mmmm', 'mnioid', 'moats', 'mobed', 'mochas', 'mochel', 'mocuck', 'mode',
            'modish', 'modist', 'modred', 'modula', 'moff', 'moggan', 'moguls', 'moil',
            'moils', 'moirai', 'mokes', 'molar', 'mold', 'moldy', 'moler', 'moles',
            'moloid', 'momism', 'mommas', 'mommy', 'momser', 'momus', 'monach', 'monica',
            'monies', 'monist', 'monont', 'moolas', 'moolvi', 'moored', 'mopane', 'mope',
            'mopier', 'mopish', 'mopsey', 'mopy', 'moray', 'morned', 'moro', 'morose',
            'mosses', 'moth', 'mother', 'motivo', 'mould', 'moulds', 'mouly', 'moxa',
            'moya', 'moyl', 'mpbs', 'mudd', 'muermo', 'muffer', 'mukluk', 'mulct',
            'mulism', 'mulla', 'muller', 'mulse', 'multum', 'mumbo', 'mume', 'mumms',
            'mund', 'mundic', 'muns', 'muon', 'mura', 'musa', 'muscae', 'musics', 'musit',
            'musjid', 'muskeg', 'musket', 'muskie', 'muskox', 'muslin', 'musmon',
            'mussel', 'musths', 'mutest', 'mutine', 'mutism', 'myall', 'mycol', 'myelin',
            'myope', 'myosin', 'myriad', 'myrtal', 'myxoma', 'nabob', 'nace', 'nacred',
            'nagel', 'naggar', 'naggle', 'naique', 'naja', 'nannie', 'napped', 'nard',
            'nardus', 'nares', 'narw', 'nasial', 'nauch', 'naut', "navy", 'neanic',
            'near', 'nebbed', 'needed', 'neetup', 'neeze', 'neger', 'nemo', 'nepit',
            "net", 'netted', 'nevada', 'nevi', 'newest', 'nicety', 'nigher', 'nighty',
            'nikon', 'nilot', 'nimbus', 'nimshi', 'nipper', 'nitrid', 'nixe', 'nizams',
            'nobbut', 'nobody', 'nocent', 'nocht', 'nocive', 'nocked', 'noctis', 'noddy',
            'nods', 'noggin', 'noggs', 'nogs', 'nohow', 'noisy', 'nold', 'nomina',
            'nonact', 'nonage', 'nonda', 'nonent', 'nonius', 'nonpar', 'noodle', 'noons',
            'norice', "norm", 'nother', 'notify', 'nubbin', 'nubias', 'nuddle', 'nuddy',
            'nudes', 'nudism', 'nudnik', 'nunc', 'nunce', 'nurl', 'nursle', 'nyalas',
            'oaks', 'oaring', 'oaves', 'obdt', 'obduce', 'obeahs', 'obese', 'obispo',
            'oblast', 'oblat', 'oblate', 'oboist', 'obolos', 'obtend', 'obtent', 'ocelli',
            'ochry', 'octads', 'oculi', 'odal', 'odder', 'odyls', 'oenone', 'offpay',
            'oftens', 'ogeed', 'ohioan', 'oiled', 'oiler', 'oinks', 'okapi', 'okee',
            'oket', 'okie', 'okra', 'okrug', 'older', 'oleary', 'olent', 'oleron',
            'oleums', 'olfact', 'olluck', 'olpae', 'oniony', 'onyx', 'onyxes', 'oogamy',
            'oolite', 'ootids', 'open', 'operas', 'opifex', 'orator', 'orch', 'orchel',
            'orchid', 'orchis', 'order', 'orders', 'ored', 'orexis', 'origan', 'orle',
            'orpin', 'orpinc', 'orvet', 'ossal', 'osse', 'ostein', 'ostent', 'ostium',
            'ostler', 'otate', 'otitis', 'otosis', 'ottar', 'ottars', 'otters', 'ourn',
            'oursel', 'ousel', 'ousted', 'outbud', 'outfed', 'outher', 'outlie', 'outly',
            'outmen', 'outsum', 'outvie', 'outwoe', 'ovenly', 'ovens', 'overgo', 'overs',
            'ovest', 'oxazin', 'oxbow', 'oxeyes', 'oxgate', 'oxland', 'ozones', 'paces',
            'pachak', 'pachas', 'pacing', 'pack', 'pager', 'pagods', 'pais', 'paise',
            'palame', 'palate', 'palch', 'pales', 'palets', 'pallar', 'pallia', 'palmer',
            'palmin', 'palms', 'palpal', 'palsy', 'paluli', 'paly', 'pand', 'panels',
            'panes', 'panfry', 'panhas', 'pankin', 'pannel', 'pants', 'panyar', 'parens',
            'pareu', 'parli', 'parnas', 'parodi', 'parole', 'parrah', 'pars', 'parson',
            'parto', 'parts', 'pask', 'passer', 'pastes', 'patefy', 'patins', 'patta',
            'pattee', 'patter', 'patuca', 'paulie', 'paves', 'pavise', 'paxwax', 'payed',
            'payees', 'peage', 'peags', 'pean', 'pearce', 'peats', 'peavie', 'pebbly',
            'pecans', 'pecket', 'pectus', 'pedler', 'peed', 'peeing', 'peeke', 'peens',
            'peep', 'pendom', 'pends', 'pengo', 'pengos', 'penny', 'pens', 'pepla',
            'peroba', 'perp', 'persic', 'persio', 'peste', 'petal', 'petter', "pew",
            'pewage', 'pewit', 'phasor', 'pheeal', 'phenyl', 'phials', 'phloem', 'phoh',
            'phono', 'photom', 'phthor', 'phycic', 'pias', 'piazza', 'picong', 'picote',
            'picry', 'pictun', 'pied', 'piend', 'pigdan', 'pight', 'piing', 'pikel',
            'piky', 'pileum', 'pily', "pin", 'pinas', 'pinjra', 'pinson', 'pinte',
            'pion', 'pipets', 'pippy', 'pirn', 'pisgah', 'pished', 'pistil', 'pitied',
            'pixel', 'pixy', 'pkgs', 'placer', 'places', 'placit', 'plaids', 'plaint',
            'plak', 'planet', 'plans', 'plant', 'plap', 'platan', 'plaud', 'plebes',
            'plebs', 'pleck', 'pleon', 'plewgh', 'plica', 'plitch', 'plonko', 'plover',
            'pluck', 'plud', 'plugs', 'plum', "plums", 'plume', 'plump', 'plumps',
            'plupf', 'plur', 'plurel', 'plyer', 'pocks', 'poco', 'podder', 'podeon',
            'podia', 'podsol', 'poilus', 'point', 'points', 'pokeys', 'poler', 'poller',
            'polyp', 'pomolo', 'pomp', 'pompon', 'ponce', 'ponces', 'pond', 'pones',
            'poney', 'pontil', 'poohs', 'poonac', 'poons', 'poorga', 'poot', 'popode',
            'porch', 'porgy', 'porter', 'portio', 'porus', 'poster', 'postic', 'postil',
            'potass', 'potch', 'potgun', 'potion', 'potman', 'potsy', 'pouser', 'pousse',
            'pranky', 'praos', 'praxis', 'prayer', 'prays', 'preach', 'prefet', 'prepg',
            'prexes', 'prexy', 'prices', 'primus', 'prio', 'prise', 'priv', 'prizes',
            'proal', 'prob', 'prober', 'proems', 'prose', 'proso', 'prys', 'psid',
            'psych', 'pteric', 'pubis', 'pubs', 'pudda', 'pudic', 'pullen', 'pumex',
            'pumper', 'pungy', 'pupil', 'purdon', 'pureed', 'purfle', 'purges', 'pusgut',
            'push', 'pusher', 'pusley', 'pyro', 'pyrone', 'pyxes', 'qanats', 'qantar',
            'quack', 'quacky', 'quail', 'quails', 'quan', 'quanti', 'quants', 'quar',
            'quarte', 'quash', 'quass', 'quatch', 'queen', 'queens', 'queet', 'quet',
            'quieti', 'quills', 'quilts', 'quinse', 'quippe', 'quippy', 'quipus',
            'quiver', 'rabat', 'rabbin', 'rabies', 'races', 'racing', 'racker', 'racons',
            'radion', 'radios', 'raffee', "rags", 'raggee', 'raggle', 'ragi', 'rake',
            'rale', 'ralish', 'ramed', 'ramjet', 'rammed', 'ramous', 'ramus', 'random',
            'ranter', 'ranty', 'rapido', 'rapper', 'rarify', 'rascal', 'rasers', 'rasoir',
            'rasure', 'ratans', 'raters', 'rats', 'ratti', 'rauque', 'rayas', 'razes',
            'reachy', 'ready', 'realm', 'reams', 'reap', 'rear', 'reason', 'reback',
            'rebank', 'rebite', 'rebold', 'rebud', "received", 'recast', 'rechew', 'recrew',
            'rect', 'rectus', 'recur', 'recut', 'redact', 'redans', 'redear', 'redwud',
            'reebok', 'reek', 'reem', 'reface', 'refeed', 'refell', 'refile', 'refill',
            'refix', 'reflag', 'reflog', 'reft', 'regard', 'regd', 'regild', 'regnum',
            'rehems', 'rehoe', 'reink', 'rejoin', 'relata', 'relick', 'relig', 'reline',
            'remast', 'remex', 'renail', 'renal', 'rentes', 'repand', 'repile', 'report',
            'requin', 'rerail', 'rerob', 'reroof', 'rerow', 'reseed', 'reshes', 'reshun',
            'reslot', 'resold', 'resown', 'rested', 'rester', 'resuck', 'resup', 'retalk',
            'retar', 'rete', 'retear', 'retent', 'retied', 'retime', 'retled', 'retore',
            'retral', 'retro', 'revet', 'revie', 'revolt', 'rewake', 'rewax', 'reyoke',
            'rfree', 'rhagon', 'rhine', 'rhombi', 'riancy', 'riata', 'ricey', 'rifest',
            'rifted', 'rifty', 'riksha', 'rillet', 'rima', 'rimula', 'rink', 'ripest',
            'rippon', 'risp', 'rivage', 'roans', 'roared', 'robert', 'robes', 'roche',
            'rocket', 'rodd', 'roddin', 'roes', 'rohun', 'roist', 'roky', 'roll',
            'rollix', 'romney', 'rompee', 'romps', 'roncet', 'rooked', 'roots', 'ropish',
            'roric', 'rort', 'rosary', 'roscid', 'roshi', 'ross', 'rotten', 'rounce',
            'rouths', 'rowdy', 'ruach', 'rubace', 'rubby', 'rube', 'rubify', 'rucker',
            'rudish', 'rudity', 'rufus', 'ruing', 'rumens', 'rummle', 'rundle', 'runes',
            'runt', 'rupia', 'rushed', 'rutin', 'rutter', 'ryania', 'sabana', 'saber',
            'sabres', 'sachem', 'saco', 'sacra', 'sacs', 'saggar', 'sagy', 'saily',
            'saimy', 'sajous', 'salamo', 'salary', 'salele', 'salep', 'salol', 'salpas',
            'saltly', 'saluda', 'salve', 'sambas', 'sambel', 'sameks', 'samian', 'samiti',
            'samoan', 'sample', 'samvat', 'sanai', 'sancta', 'sand', 'sane', 'sans',
            'sapid', 'sapo', 'sarape', 'sardel', 'sarge', 'sarin', 'sarlak', 'sarpo',
            'satang', 'satrap', 'satsop', 'satyr', 'sauces', 'sauna', 'sautes', 'save',
            'savers', 'savola', 'savour', 'sawing', 'scabia', 'scalar', 'scalma',
            'scapha', 'scarcy', 'scary', 'scats', 'scaup', 'scelp', 'scharf', 'schema',
            'schone', 'school', 'schoon', 'schrik', 'sciage', 'sclera', 'scliff', 'scoad',
            'scold', 'scomm', 'scoria', 'scorse', 'scots', 'scovy', 'scow', 'scowed',
            'scowls', 'scrae', 'scraps', 'scrawl', 'scream', 'screes', 'screve', 'screws',
            'scrin', 'scrite', 'scroff', 'scrogs', 'scrubs', 'scruft', 'scrunt', 'scryer',
            'scud', 'sculsh', 'scult', 'seawan', 'sebkha', 'secess', 'secpar', 'sedile',
            'seege', 'seer', 'seggio', 'segou', 'seiche', 'seimas', 'sele', 'selion',
            'semel', 'sempre', 'senage', 'sengi', 'senna', 'sennit', 'senso', 'seoul',
            'sephen', 'sepium', 'sept', 'septa', 'septum', 'seqed', 'sero', 'serous',
            'serran', 'served', 'sess', 'settos', 'seve', 'sewage', 'sewing', 'sexism',
            'sfree', 'shanna', 'shaped', 'shardy', 'sharif', 'sharky', 'shee', 'sheel',
            'sheepy', 'sheeve', 'shema', 'shent', 'sherds', 'sheria', 'sheuch', 'shew',
            'shield', 'shies', 'shifty', 'shih', 'shikra', 'shikse', 'shilf', 'shisn',
            'shiver', 'shod', 'shoddy', 'shohet', 'shoo', 'shoots', 'shop', 'shouse',
            'showed', 'shradh', 'shrews', 'shtetl', 'shucks', 'sibbs', 'sicc', 'sicced',
            'sicked', 'sides', 'sidth', 'siena', 'sievy', 'sigh', 'sigla', 'siker',
            'silex', 'sills', 'silure', 'silva', 'sims', 'simurg', 'sinew', 'singed',
            'sink', 'sinks', 'sins', 'siper', 'sipper', 'sish', 'sisith', 'situla',
            'situp', 'siva', 'sizars', 'sizz', 'sizzle', 'skee', 'skeets', 'skeily',
            'skein', 'skelp', 'sker', 'skirp', 'skit', 'skited', 'skits', 'skitty',
            'skulls', 'skunky', 'skurry', 'skyish', 'skyman', 'slacks', 'slaps', 'slater',
            'slav', 'slave', 'slavey', 'slete', 'sleuth', 'slims', "slip", 'slive',
            'slop', 'slot', "slotted", 'slots', 'sloush', 'slow', 'slowup', "slum",
            'slumpy', 'slunk', 'slurb', 'slutty', 'smalls', 'smaltz', 'smeek', 'smiled',
            'smiley', 'smolts', 'smouse', 'smout', 'smug', 'smurks', 'smurry', 'smutch',
            'snag', 'snails', 'snappy', 'snatch', 'snaws', 'sneezy', 'snift', 'snirl',
            'snits', 'snobs', 'snore', 'snowie', 'soaps', 'soared', 'sobeit', 'sober',
            'socko', "sod", 'sodio', 'sofar', 'softa', 'soho', 'soka', 'sokes', 'solar',
            'solary', 'soles', 'solus', 'somers', 'sompne', 'song', 'songy', 'sonic',
            'soniou', 'sooky', 'sool', 'sopher', 'sopor', 'sopors', 'sori', 'sosie',
            'soud', 'souls', 'soulz', 'soumak', 'sovite', 'sowers', 'spacy', 'spaer',
            'spaked', 'span', 'spaver', 'specie', 'spelk', 'sphere', 'spial', 'spiked',
            'spill', 'spinal', 'spirae', 'spirit', 'spited', 'spitz', 'spoke', 'spoken',
            'spook', 'spoors', 'sporal', 'spot', 'spout', 'spried', 'spring', 'sprit',
            'spruer', 'spuing', 'spurns', 'sput', 'spydom', 'spyism', 'squeak', 'squet',
            'squirm', 'staab', 'stadda', 'stagey', 'staid', 'stalls', 'stane', 'staphs',
            'staplf', 'stasis', 'states', 'staw', 'stawn', 'stay', 'stddmp', 'steady',
            'steg', 'stenos', "step", 'stert', 'steven', 'stib', 'sties', 'stife',
            'stiff', 'stilet', 'stipel', 'stitch', 'stith', 'stoga', 'stoit', 'stold',
            'stoles', 'stolon', 'stoner', 'stonk', 'stoof', 'stoond', 'stop', 'stoper',
            'storey', 'stour', 'stoush', 'stouty', 'stowth', 'strake', 'strany', 'strati',
            'streep', 'strig', 'striga', 'strums', 'studdy', 'studia', 'stuggy', 'stupid',
            'styca', 'styful', 'styled', 'suade', 'subaud', 'subch', 'subgod', 'sublot',
            'subman', 'subvii', 'sucks', 'sucres', 'sudary', 'suers', 'sugat', 'suggil',
            'sughs', 'suivez', 'sulfo', 'sulky', "sum", 'sumach', 'sumpit', 'sungar',
            'sunkie', 'sunlet', 'sunny', 'sunyie', 'supper', 'suppos', 'surah', 'surat',
            'surf', 'surnap', 'surnay', 'surtax', 'survey', 'susan', 'sushi', 'suttee',
            'swabby', 'swaddy', 'swaggy', 'swains', 'swamps', 'swarm', 'swashy', 'sweep',
            'sweese', 'sweven', 'swig', 'swiple', 'swirls', 'swived', 'swobs', 'syddir',
            'synced', 'syndic', 'syne', 'synop', 'syriac', 'syrus', 'tabac', 'tabi',
            'tabus', 'tacked', 'tacts', 'tagua', 'tahina', 'taiaha', 'taiga', 'taints',
            'taipan', 'taiwan', 'tali', 'talk', 'taller', 'talmas', 'talmud', 'talose',
            'tammie', 'tampon', 'tanbur', 'tandem', 'tanier', 'tape', 'tapet', 'taping',
            'taraf', 'tarage', 'tarbet', 'tardle', 'tarea', 'tarmac', 'tarocs', 'tattoo',
            'tatu', 'taurus', 'tauter', 'tavell', 'tavers', 'tawdry', 'tawers', 'tawpy',
            'tawsed', 'taxa', 'taxed', 'taxman', 'teaboy', 'teache', 'teaish', 'teals',
            'team', 'teased', 'teched', 'tecon', 'tedge', 'teed', 'teedle', 'teemer',
            'teeny', 'tegua', 'teguas', 'teise', 'tejano', 'telesm', 'telia', 'tell',
            'tendre', 'tenent', 'tenet', 'tenez', 'tenio', 'tensed', 'tentor', 'tenty',
            'tenues', 'tenuto', 'teopan', 'tepee', 'tepees', 'teras', 'tercia', 'tesack',
            'teslas', 'testar', 'teuch', 'tewed', 'tews', 'texans', 'thaw', 'thecae',
            'thegns', 'theins', 'theme', 'thenar', 'theses', 'theta', 'thetic', 'thigh',
            'thill', 'thilly', 'thomas', 'thong', 'thoric', 'threep', 'threne', 'throve',
            'thru', 'thump', 'thuya', 'thymi', 'thymin', 'tiaras', 'tibey', 'tier',
            'tierer', 'ties', 'tikis', 'tikkun', 'tikur', 'tildes', 'tilery', 'timor',
            'tinged', 'tinily', 'tink', 'tints', 'tishri', 'titano', 'titans', 'titule',
            'toat', 'toch', 'tods', 'toilet', 'tokays', 'tolsey', 'toomly', 'toop',
            'topepo', 'toper', 'topsl', 'torc', 'tormae', 'tormen', 'torse', 'torsel',
            'torsk', 'tory', 'tosca', 'toss', 'tost', 'touter', 'towdie', 'towel',
            'towson', 'toxity', 'toydom', 'toyers', 'toyish', 'toyon', 'trabu', 'trade',
            'tragal', 'traily', 'trame', 'trank', 'trapan', 'trashy', 'trav', 'tread',
            'trees', 'treget', 'tremex', 'tremie', 'trepak', 'trepan', 'trey', 'triced',
            'trier', 'triga', 'trigo', 'trikir', 'trityl', 'trock', 'trompe', 'tronc',
            'troot', 'troppo', 'trot', 'trow', 'troy', 'troys', 'truced', 'trucks',
            'trues', 'trug', 'trumps', 'truss', 'truths', 'tsade', 'tsamba', 'tsktsk',
            'tubbal', 'tubbie', 'tubes', 'tuchis', 'tuft', 'tufty', 'tugui', 'tuliac',
            'tumbly', 'tumors', 'tuners', 'tunful', 'tungah', 'tupelo', 'tupian', 'tuple',
            'tuque', 'turken', 'turma', 'turnup', 'turps', 'tushy', 'tuttis', 'twang',
            'tweet', 'twerp', 'twerps', 'twibil', 'twicer', 'twie', 'twiers', 'twint',
            'twisel', 'twitty', 'tyburn', 'tyloma', 'tylote', 'tynd', 'tyned', 'typhon',
            'typhus', 'typify', 'tyros', 'tzetse', 'uakari', 'uberty', 'udders', 'uglis',
            'ugly', 'ulemas', 'ullage', 'ulnage', 'ultion', 'ulto', 'ultra', 'umiri',
            'unakin', 'unbow', 'unchic', 'uncini', 'unclay', 'unclip', 'uncoil', 'uncoin',
            'uncork', 'uncrib', 'undrag', 'unedge', 'unepic', 'unflag', 'unfoxy', 'unfur',
            'ungamy', 'ungear', 'ungown', 'ungula', 'ungull', 'unhale', 'unhazy',
            'unioid', 'unity', 'unkid', 'unknow', 'unlace', 'unlaw', 'unlays', 'unleft',
            'unmast', 'unnice', 'unorn', 'unride', 'unrigs', 'unrued', 'unsad', 'unsex',
            'unshod', 'unshut', 'unsore', 'unsoul', 'untaut', 'unties', 'untune',
            'unwarn', 'unwed', 'unwind', 'unwist', 'unwive', 'upband', 'upbank', 'upby',
            'upends', 'upgrew', 'uphove', 'uphurl', 'uplook', 'upmost', 'uppile',
            'uppour', 'upseek', 'upsit', 'upspin', 'upstem', 'uptide', 'uptorn', 'uptube',
            'upward', 'upways', 'upwrap', 'urali', 'urbs', 'ureide', 'urgent', 'uroo',
            'uropod', 'urushi', 'usage', 'usenet', 'using', 'usnic', 'usurp', 'utahan',
            'utum', 'uveal', 'vacuua', 'vagina', 'vaguio', 'vainly', 'vakil', 'valewe',
            'valyl', 'vamper', 'vannet', 'vappa', 'varech', 'varier', 'varios', 'varna',
            'varved', 'vasts', "vat", 'vatman', 'vatter', 'vaults', 'vaunt', 'vaus',
            'vedro', 'veduis', 'veenas', 'vegan', 'veiny', 'velary', 'velvet', 'venere',
            'venged', 'venial', 'venine', 'vent', 'verged', 'verist', 'versor', 'verve',
            'vervet', 'vesses', 'vetust', 'vibe', 'vibes', 'vibex', 'vigil', 'vigor',
            'vimana', 'vineal', 'vinew', 'vining', 'virgal', 'virger', 'virole', 'virose',
            'viscum', 'vises', 'vitium', 'vitra', 'volar', 'voled', 'volens', 'volga',
            'vorage', 'voteen', 'vvll', 'wadis', 'wady', 'waft', 'waggie', 'wahwah',
            'waily', 'wakeel', 'wakken', 'walk', 'walrus', 'walsh', 'walty', 'wammus',
            'wangan', 'wanlas', 'wanny', 'wapped', 'warble', 'warly', 'warmen', 'warnt',
            'warran', 'warrer', 'wash', 'washen', 'wasn', 'waspy', 'watap', 'waumle',
            'wauve', 'waxand', 'waxer', 'wayaka', 'weaky', 'wealds', 'wealth', 'wears',
            'wedged', 'wedgy', 'weedow', 'weent', 'weever', 'weeze', 'wekeen', 'welk',
            'wemmy', 'wench', 'wend', 'wendic', 'went', 'wert', 'wesley', 'wetly',
            'whack', 'whacks', 'whacky', 'whap', 'whare', "what", 'wheep', 'wheezy',
            "when", 'where', 'wheres', 'which', 'whimmy', 'whined', 'whiney', 'whirry',
            "who", 'whores', 'whorl', 'whoso', 'whydah', 'whys', 'wibble', 'widish',
            'wield', 'wigdom', 'wiggy', 'wiking', 'wilga', 'willie', 'wilton', 'winey',
            'winks', 'wisped', 'wissle', 'wister', 'wists', 'witan', 'witful', 'withed',
            'withes', 'witter', 'woilie', 'woleai', 'wolves', 'wone', 'wooed', 'wooing',
            'wool', 'woons', 'wopsy', 'worlds', 'worsts', 'wounds', 'wrangs', 'wreat',
            'wren', 'wrests', 'wrings', 'write', 'wulk', 'wurley', 'wust', 'wynns',
            'xctl', 'xenian', 'xeres', 'xiii', 'xray', 'xystus', 'yaba', 'yabbie',
            'yaffil', 'yaffle', 'yager', 'yair', 'yakshi', 'yale', 'yali', 'yalla',
            'yamun', 'yang', 'yank', 'yanked', 'yanky', 'yapok', 'yapon', 'yaqona',
            "yard", 'yarner', 'yauds', 'yawps', 'yblent', 'yclept', 'year', 'yearn',
            'yearns', 'yede', 'yellow', 'yenned', 'yeoman', 'yerb', 'yesty', 'yhwh',
            'yippee', 'yizkor', 'yobbos', 'yobi', 'yodh', 'yogic', 'yojan', 'yokel',
            'yokes', 'yolked', 'yomim', 'yook', 'youngs', 'yoven', 'yowled', 'yowls',
            'yuman', 'zaffar', 'zaffer', 'zaffre', 'zafree', 'zagaie', 'zaire', 'zaires',
            'zakah', 'zander', 'zanily', 'zapas', 'zaqqum', 'zeiss', 'zemmi', 'zenick',
            'zieger', 'zigs', 'zilch', 'zincs', 'zink', 'ziti', 'zizel', 'zizit', 'zoaea',
            'zoeas', 'zoid', 'zolle', 'zonda', 'zonure', "zoo", 'zoozoo', 'zoster',
            'zygion', 'zygite', 'zygoid', 'zymite']
